; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = heltec_wifi_lora_32_V3
; for env:vision-master-e190
; src_dir = tft_src
; for env:vision-master-e290
; src_dir = eink_src
; for env:heltec_wifi_lora_32_V3
; src_dir = src ;;Default
; for heltec_wifi_lora_32_V3-test-signal-generator
; src_dir = trans_src
; for ELRS-BOARDS
; src_dir = elrs-boards
;src_dir = radio

[env:heltec_wifi_lora_32_V3]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
upload_speed = 921600
monitor_speed = 115200
board_build.f_cpu = 240000000
board_build.filesystem = littlefs
lib_deps = 
	ropg/Heltec_ESP32_LoRa_v3@^0.9.1
	ESP32Async/AsyncTCP
	ESP32Async/ESPAsyncWebServer
build_flags = 
	-DHELTEC_POWER_BUTTON
	-DHELTEC
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1

; Heltec WiFi LORA 32 V3 - V3.2
; display is external now
[env:heltec_wifi_lora_32_V3_2]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
upload_speed = 921600
monitor_speed = 115200
board_build.f_cpu = 240000000
board_build.filesystem = littlefs
lib_deps = 
	ropg/Heltec_ESP32_LoRa_v3@^0.9.1
	ESP32Async/AsyncTCP
	ESP32Async/ESPAsyncWebServer
build_flags = 
	-DHELTEC_POWER_BUTTON
	-DHELTEC
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
	-DHELTEC_WIFI_LORA_32_V3_2

[env:heltec_wifi_lora_32_V3_lora-TX-scanner]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
upload_speed = 921600
monitor_speed = 115200
board_build.f_cpu = 240000000
board_build.filesystem = littlefs
lib_deps = 
	ropg/Heltec_ESP32_LoRa_v3@^0.9.1
	ESP Async WebServer
build_flags = 
	-DHELTEC_POWER_BUTTON
	-DHELTEC
	-DSAMPLES_RSSI=5
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
	-DDEFAULT_RX=916
	-DDEFAULT_TX=915
	-DDEFAULT_LORA_ENABLED=true
	-DDEFAULT_LORA_TX_POWER=22
	-DDEFAULT_LORA_SF=12
	
[env:heltec_wifi_lora_32_V3-OSD]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
upload_speed = 921600
monitor_speed = 115200
board_build.f_cpu = 240000000
board_build.filesystem = littlefs
lib_deps = 
	ropg/Heltec_ESP32_LoRa_v3@^0.9.1
	bblanchon/ArduinoJson@^7.2.0
	ESP Async WebServer
build_flags = 
	-DHELTEC_POWER_BUTTON
	-DHELTEC
	-DOSD_ENABLED
	-DOSD_SIDE_BAR
	-DSAMPLES_RSSI=5
	-DFREQ_BEGIN=850
	-DFREQ_END=960
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
	-DOSD_DOT_DISPLAY
	-DSIDEBAR_START_ROW=2
	-DOSD_CHART_START_ROW=14

[env:heltec_wifi_lora_32_V3-OSD-LORA]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
upload_speed = 921600
monitor_speed = 115200
board_build.f_cpu = 240000000
board_build.filesystem = littlefs
lib_deps = 
	ropg/Heltec_ESP32_LoRa_v3@^0.9.1
	bblanchon/ArduinoJson@^7.2.0
	ESP Async WebServer
build_flags = 
	-DHELTEC_POWER_BUTTON
	-DHELTEC
	-DOSD_ENABLED
	-DOSD_SIDE_BAR
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
	-DOSD_DOT_DISPLAY
	-DDEFAULT_RX=916
	-DDEFAULT_TX=915
	-DDEFAULT_LORA_ENABLED=true
	-DDEFAULT_LORA_TX_POWER=22
	-DDEFAULT_LORA_SF=12
	-DOSD_BAR_CHAR="\"\.\""

[env:heltec_wifi_lora_32_V3_433]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
upload_speed = 921600
monitor_speed = 115200
board_build.f_cpu = 240000000
board_build.filesystem = littlefs
lib_deps = 
	ropg/Heltec_ESP32_LoRa_v3@^0.9.1
	ESP Async WebServer
build_flags = 
	-DHELTEC_POWER_BUTTON
	-DHELTEC
	-DFREQ_BEGIN=130
	-DFREQ_END=180
	-DFREQ_RX=133
	-DRADIOLIB_CHECK_PARAMS=0

[env:lilygo-T3S3-v1-2-sx1262]
platform = espressif32
board = t3_s3_v1_x
framework = arduino
upload_speed = 921600
monitor_speed = 115200
board_build.f_cpu = 240000000
board_build.filesystem = littlefs
lib_deps = 
	ropg/Heltec_ESP32_LoRa_v3@^0.9.1
	RadioLib
	U8g2
	XPowersLib
	ESP Async WebServer
build_flags = 
	-DLILYGO
	-DT3_S3_V1_2_SX1262
	-DT3_V1_3_SX1262
	-DARDUINO_LILYGO_T3S3_SX1262
	-DESP32
	-DUSING_SX1262
	-DARDUINO_ARCH_ESP32
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_LILYGO_T3_S3_V1_X
	-DARDUINO_USB_MODE=1

[env:lilygo-T3S3-v1-2-sx1262-lora-RX-host-reciver]
platform = espressif32
board = t3_s3_v1_x
framework = arduino
upload_speed = 921600
monitor_speed = 115200
board_build.f_cpu = 240000000
board_build.filesystem = littlefs
lib_deps = 
	ropg/Heltec_ESP32_LoRa_v3@^0.9.1
	RadioLib
	U8g2
	XPowersLib
	ESP Async WebServer
build_flags = 
	-DLILYGO
	-DT3_S3_V1_2_SX1262
	-DT3_V1_3_SX1262
	-DARDUINO_LILYGO_T3S3_SX1262
	-DESP32
	-DUSING_SX1262
	-DARDUINO_ARCH_ESP32
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_LILYGO_T3_S3_V1_X
	-DARDUINO_USB_MODE=1
	-DDEFAULT_RX=916
	-DDEFAULT_TX=915
	-DDEFAULT_LORA_ENABLED=true
	-DDEFAULT_IS_LORA_HOST=true
	-DDISPLAY_RAW_SCAN=1
	-DDEFAULT_LORA_SF=12

[env:lilygo-T3S3-v1-2-lr1121-2400]
platform = espressif32
board = t3_s3_v1_x
framework = arduino
upload_speed = 921600
monitor_speed = 115200
board_build.f_cpu = 240000000
board_build.filesystem = littlefs
lib_deps = 
	ropg/Heltec_ESP32_LoRa_v3@^0.9.1
	RadioLib
	U8g2
	XPowersLib
	ESP Async WebServer
build_flags = 
	-DLILYGO
	-DT3_S3_V1_2_LR1121
	-DARDUINO_LILYGO_T3S3_LR1121
	-DESP32
    -DSAMPLES_RSSI=5
	-DUSING_LR1121
    -DFREQ_BEGIN=2400
	-DFREQ_END=2500
	-DFREQ_RX=2440
	-DARDUINO_ARCH_ESP32
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_LILYGO_T3_S3_V1_X
	-DARDUINO_USB_MODE=1

[env:lilygo-T3S3-v1-2-lr1121-900]
platform = espressif32
board = t3_s3_v1_x
framework = arduino
upload_speed = 921600
monitor_speed = 115200
board_build.f_cpu = 240000000
board_build.filesystem = littlefs
lib_deps = 
	ropg/Heltec_ESP32_LoRa_v3@^0.9.1
	RadioLib
	U8g2
	XPowersLib
	ESP Async WebServer
build_flags = 
	-DLILYGO
	-DT3_S3_V1_2_LR1121
	-DARDUINO_LILYGO_T3S3_LR1121
	-DESP32
    -DSAMPLES_RSSI=5
	-DUSING_LR1121
	-DINIT_FREQ=900
    -DFREQ_BEGIN=830
	-DFREQ_END=945
	-DFREQ_RX=2440
	-DARDUINO_ARCH_ESP32
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_LILYGO_T3_S3_V1_X
	-DARDUINO_USB_MODE=1

[env:lilygo-T3S3-v1-2-lr1121-900-radio-tx]
platform = espressif32
board = t3_s3_v1_x
framework = arduino
upload_speed = 921600
monitor_speed = 115200
board_build.f_cpu = 240000000
board_build.filesystem = littlefs
src_dir = radio
lib_deps = 
	ropg/Heltec_ESP32_LoRa_v3@^0.9.1
	RadioLib
	XPowersLib
	SPI
	https://github.com/bolderflight/sbus
	gitlab-airbornemint/Protothreads
build_flags = 
 	-DMAIN_FILE="Tx.cpp"
	-DLILYGO
	-DT3_S3_V1_2_LR1121
	-DARDUINO_LILYGO_T3S3_LR1121
	-DESP32
    -DSAMPLES_RSSI=5
	-DUSING_LR1121
	-DINIT_FREQ=900
    -DFREQ_BEGIN=830
	-DFREQ_END=945
	-DFREQ_RX=2440
	-DARDUINO_ARCH_ESP32
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_LILYGO_T3_S3_V1_X
	-DARDUINO_USB_MODE=1
	-DLORA_RX=0
	-DLORA_TX=1

[env:lilygo-T3S3-v1-2-lr1121-900-radio-rx]
platform = espressif32
board = t3_s3_v1_x
framework = arduino
upload_speed = 921600
monitor_speed = 115200
board_build.f_cpu = 240000000
board_build.filesystem = littlefs
src_dir = radio
lib_deps = 
	ropg/Heltec_ESP32_LoRa_v3@^0.9.1
	RadioLib
	XPowersLib
	https://github.com/bolderflight/sbus
	gitlab-airbornemint/Protothreads
build_flags = 
 	-DMAIN_FILE="Tx.cpp"
	-DLILYGO
	-DT3_S3_V1_2_LR1121
	-DARDUINO_LILYGO_T3S3_LR1121
	-DESP32
    -DSAMPLES_RSSI=5
	-DUSING_LR1121
	-DINIT_FREQ=900
    -DFREQ_BEGIN=830
	-DFREQ_END=945
	-DFREQ_RX=2440
	-DARDUINO_ARCH_ESP32
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_LILYGO_T3_S3_V1_X
	-DARDUINO_USB_MODE=1
	-DLORA_RX=1
	-DLORA_TX=0

[env:heltec-v3-900-radio-rx]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
upload_speed = 921600
monitor_speed = 115200
board_build.f_cpu = 240000000
src_dir = radio
lib_deps = 
	ropg/Heltec_ESP32_LoRa_v3@^0.9.1
	RadioLib
	XPowersLib
	https://github.com/bolderflight/sbus
	mbed-takuhachisu/CRC8
build_flags = 
 	-DMAIN_FILE="Tx.cpp"
	-DHELTEC_POWER_BUTTON
	-DHELTEC
	-DRADIOLIB_CHECK_PARAMS=0
	-DESP32
	-DARDUINO_ARCH_ESP32
	-DARDUINO_USB_CDC_ON_BOOT=0
	-DARDUINO_USB_MODE=1
	-DLORA_RX=1
	-DLORA_TX=0

[env:heltec-v3-900-radio-tx]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
upload_speed = 921600
monitor_speed = 115200
board_build.f_cpu = 240000000
src_dir = radio
lib_deps = 
	ropg/Heltec_ESP32_LoRa_v3@^0.9.1
	RadioLib
	XPowersLib
	https://github.com/bolderflight/sbus
	mbed-takuhachisu/CRC8
build_flags = 
 	-DMAIN_FILE="Tx.cpp"
	-DHELTEC_POWER_BUTTON
	-DHELTEC
	-DRADIOLIB_CHECK_PARAMS=0
	-DESP32
	-DARDUINO_ARCH_ESP32
	-DARDUINO_USB_CDC_ON_BOOT=0
	-DARDUINO_USB_MODE=1
	-DLORA_RX=0
	-DLORA_TX=1
	-DSERIAL_INPUT=1

[env:lilygo-T3S3-v1-2-sx1262-900-radio-rx]
platform = espressif32
board = t3_s3_v1_x
framework = arduino
upload_speed = 921600
monitor_speed = 115200
board_build.f_cpu = 240000000
board_build.filesystem = littlefs
src_dir = radio
lib_deps = 
	ropg/Heltec_ESP32_LoRa_v3@^0.9.1
	RadioLib
	XPowersLib
	duracopter/MAVLink v2 C library@^2.0
build_flags = 
 	-DMAIN_FILE="Tx.cpp"
	-DLILYGO
	-DT3_S3_V1_2_SX1262
	-DARDUINO_LILYGO_T3S3_SX1262
	-DESP32
    -DSAMPLES_RSSI=5
	-DUSING_SX1262
	-DINIT_FREQ=900
    -DFREQ_BEGIN=830
	-DFREQ_END=945
	-DFREQ_RX=2440
	-DARDUINO_ARCH_ESP32
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_LILYGO_T3_S3_V1_X
	-DARDUINO_USB_MODE=1
	-DLORA_RX=1
	-DLORA_TX=0

[env:lilygo-T3S3-v1-2-lr1121-900-BT]
platform = espressif32
board = t3_s3_v1_x
framework = arduino
upload_speed = 921600
monitor_speed = 115200
board_build.f_cpu = 240000000
board_build.filesystem = littlefs
lib_deps = 
	ropg/Heltec_ESP32_LoRa_v3@^0.9.1
	RadioLib
	U8g2
	XPowersLib
	h2zero/NimBLE-Arduino
build_flags = 
	-DLILYGO
	-DT3_S3_V1_2_LR1121
	-DARDUINO_LILYGO_T3S3_LR1121
	-DESP32
    -DSAMPLES_RSSI=5
	-DUSING_LR1121
	-DINIT_FREQ=900
    -DFREQ_BEGIN=830
	-DFREQ_END=945
	-DFREQ_RX=2440
	-DARDUINO_ARCH_ESP32
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_LILYGO_T3_S3_V1_X
	-DARDUINO_USB_MODE=1
	-DBT_MOBILE

[env:lilygo-T3S3-v1-2-lr1121-900-compass]
platform = espressif32
board = t3_s3_v1_x
framework = arduino
upload_speed = 1500000
monitor_speed = 115200
board_build.f_cpu = 240000000
board_build.partitions = min_spiffs.csv
board_build.filesystem = littlefs
lib_deps = 
	ropg/Heltec_ESP32_LoRa_v3@^0.9.1
	RadioLib
	XPowersLib
	h2zero/NimBLE-Arduino
	https://github.com/Genaker/Adafruit_HMC5883_Unified
build_flags =
	-lbt
	-Og -ggdb3
	-DLILYGO
	-DT3_S3_V1_2_LR1121
	-DARDUINO_LILYGO_T3S3_LR1121
	-DESP32
    -DSAMPLES_RSSI=2
	-DUSING_LR1121
	-DSCAN_RBW_FACTOR=1
	-DINIT_FREQ=900
    -DFREQ_BEGIN=800
	-DFREQ_END=950
	-DFREQ_RX=2440
	-DARDUINO_ARCH_ESP32
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_LILYGO_T3_S3_V1_X
	-DARDUINO_USB_MODE=1
	-DCOMPASS_ENABLED
	-DCOMPASS_FREQ=915
	-DCOMPASS_DEBUG2
	-DCOMPASS_RSSI
	-DBT_MOBILE
	-DBT_RSSI
	-DBT_NM

[env:lilygo-T3S3-v1-2-sx1280]
platform = espressif32
board = t3_s3_v1_x
framework = arduino
upload_speed = 921600
monitor_speed = 115200
board_build.f_cpu = 240000000
board_build.filesystem = littlefs
lib_deps = 
	ropg/Heltec_ESP32_LoRa_v3@^0.9.1
	RadioLib
	U8g2
	XPowersLib
	ESP Async WebServer
build_flags = 
	-DLILYGO
	-DT3_S3_V1_2_SX1280_PA
	-DARDUINO_LILYGO_T3S3_SX1280_PA
	-DESP32
	-DUSING_SX1280PA
	-DFREQ_BEGIN=2400
	-DFREQ_END=2500
	-DFREQ_RX=2440
	-DARDUINO_ARCH_ESP32
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_LILYGO_T3_S3_V1_X
	-DARDUINO_USB_MODE=1
	-DSERIAL_OUT

[env:lilygo-T3-v1-6-xs1276]
platform = espressif32
board = esp32dev
framework = arduino
upload_speed = 115200
monitor_speed = 115200
board_build.filesystem = littlefs
lib_deps = 
	ropg/Heltec_ESP32_LoRa_v3@^0.9.1
	RadioLib
	U8g2
	XPowersLib
	ESP Async WebServer
build_flags =
	-DLILYGO
	-DT3_V1_6_SX1276
	-DUSING_SX1276
	-DESP32
	-DARDUINO_ARCH_ESP32
	-DARDUINO_USB_CDC_ON_BOOT=0 ;; if not 0 - Serial issue 
	-DARDUINO_LILYGO_T3_V1_6
	-DARDUINO_USB_MODE=1

;; More old lylygo/titygo boeads defenitions you can find here:
;; https://github.com/PTR-projects/PTR_GroundStation_firmware/blob/main/platformio.ini
;; https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/blob/master/platformio.ini

[env:heltec_wifi_lora_32_V3-test-signal-generator]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
upload_speed = 115200
monitor_speed = 115200
board_build.f_cpu = 240000000
board_build.flash_size = 80000000L
lib_deps = 
	ropg/Heltec_ESP32_LoRa_v3@^0.9.1
build_flags = 
	-DHELTEC
	-DHELTEC_POWER_BUTTON

[env:vision-master-e290]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
board_upload.use_1200bps_touch = true
build_flags =
	-DHELTEC
	-DHELTEC_BOARD=37
	-DSLOW_CLK_TPYE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DLoRaWAN_DEBUG_LEVEL=0
	-DE290
	-DESP32
	-DVision_Master_E290
	-DRADIOLIB_EXCLUDE_CC1101=true
	-DRADIOLIB_EXCLUDE_LR11x0=true
	-DRADIOLIB_EXCLUDE_NRF24=true
	-DRADIOLIB_EXCLUDE_RF69=true
	-DRADIOLIB_EXCLUDE_RFM2X=true
	-DRADIOLIB_EXCLUDE_SI443X=true
	-DRADIOLIB_EXCLUDE_SX1231=true
	-DRADIOLIB_EXCLUDE_SX127X=true
	-DRADIOLIB_EXCLUDE_SX128X=true
lib_deps = 
	SPI
	Wire
	adafruit/Adafruit BusIO @ 1.9.6
	https://github.com/HelTecAutomation/Heltec_ESP32/
	adafruit/Adafruit GFX Library@^1.11.10
	ropg/Heltec_ESP32_LoRa_v3@^0.9.1

[env:vision-master-t190]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
board_upload.use_1200bps_touch = true
build_flags = 
	-DHELTEC
	-DHELTEC_BOARD=38
	-DSLOW_CLK_TPYE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DLoRaWAN_DEBUG_LEVEL=0
	-DT190
	-DESP32
	-DVision_Master_T190
	-DRADIOLIB_EXCLUDE_CC1101=true
	-DRADIOLIB_EXCLUDE_LR11x0=true
	-DRADIOLIB_EXCLUDE_NRF24=true
	-DRADIOLIB_EXCLUDE_RF69=true
	-DRADIOLIB_EXCLUDE_RFM2X=true
	-DRADIOLIB_EXCLUDE_SI443X=true
	-DRADIOLIB_EXCLUDE_SX1231=true
	-DRADIOLIB_EXCLUDE_SX127X=true
	-DRADIOLIB_EXCLUDE_SX128X=true
	-DROTATION=1 # 1 = default; 3 = inverted

lib_deps = 
	SPI
	Wire
	adafruit/Adafruit BusIO @ 1.9.6
	https://github.com/HelTecAutomation/Heltec_ESP32/
	adafruit/Adafruit GFX Library@^1.11.10
	ropg/Heltec_ESP32_LoRa_v3@^0.9.1
	adafruit/Adafruit ST7735 and ST7789 Library@^1.10.4

[env:seek-on-mavic-sx1280]
platform = espressif32
board = t3_s3_v1_x
framework = arduino
upload_speed = 921600
monitor_speed = 115200
board_build.f_cpu = 240000000
board_build.filesystem = littlefs
lib_deps = 
	ropg/Heltec_ESP32_LoRa_v3@^0.9.1
	RadioLib
	U8g2
	XPowersLib
	ESP Async WebServer
build_flags = 
	-DLILYGO
	-DT3_S3_V1_2_SX1280_PA
	-DARDUINO_LILYGO_T3S3_SX1280_PA
	-DESP32
	-DUSING_SX1280PA
    -DFREQ_BEGIN=2410
	-DFREQ_END=2452
	-DARDUINO_ARCH_ESP32
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_LILYGO_T3_S3_V1_X
	-DARDUINO_USB_MODE=1
	-DLOG_DATA_JSON=1
	-DSERIAL_OUT
	-DTX_PIN=43 # TX pin on the Lora board, hook up to RX pin on Pi
	-DRX_PIN=16 # not used but still need to be defined
	-DSEEK_ON_X=1 # seek on X, so use HW serial port to log JSON
	-DBANDWIDTH=4.8
	-DDISABLE_SDCARD

[env:seek-on-mavic-lr1121]
platform = espressif32
board = t3_s3_v1_x
framework = arduino
upload_speed = 921600
monitor_speed = 115200
board_build.f_cpu = 240000000
board_build.filesystem = littlefs
lib_deps = 
	ropg/Heltec_ESP32_LoRa_v3@^0.9.1
	RadioLib
	U8g2
	XPowersLib
	ESP Async WebServer
build_flags = 
	-DLILYGO
	-DT3_S3_V1_2_LR1121
	-DT3_V1_3_SX1262
	-DARDUINO_LILYGO_T3S3_LR1121
	-DESP32
    -DSAMPLES_RSSI=5
	-DUSING_LR1121
    -DFREQ_BEGIN=2410
	-DFREQ_END=2452
	-DARDUINO_ARCH_ESP32
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_LILYGO_T3_S3_V1_X
	-DARDUINO_USB_MODE=1
	-DLOG_DATA_JSON=1
	-DSERIAL_OUT
	-DTX_PIN=43 # TX pin on the Lora board, hook up to RX pin on Pi
	-DRX_PIN=16 # not used but still need to be defined
	-DSEEK_ON_X=1 # seek on X, so use HW serial port to log JSON
	-DBANDWIDTH=4.8
	-DDISABLE_SDCARD

[env:ESP32-PICO-D4-ELRS]
platform = espressif32
board = esp32dev
framework = arduino
upload_speed = 115200
monitor_speed = 115200
build_flags = 
	-DESP32
    -DSAMPLES_RSSI=5
	-DUSING_LR1121
    -DFREQ_BEGIN=2410
	-DFREQ_END=2452
	-DARDUINO_ARCH_ESP32
	-DARDUINO_USB_CDC_ON_BOOT=0
	-DARDUINO_USB_MODE=1
	-DSERIAL_OUT
	-DDISABLE_SDCARD
lib_deps = 
	RadioLib

[env:native]
platform = native
